"""add relationship

Revision ID: 87ffde5400ff
Revises: 1770ae02775e
Create Date: 2025-03-23 15:29:24.874129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ffde5400ff'
down_revision: Union[str, None] = '1770ae02775e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title_index', 'tasks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title_index', table_name='tasks')
    # ### end Alembic commands ###
