"""add more things

Revision ID: ae4725dfad5b
Revises: 87ffde5400ff
Create Date: 2025-04-03 15:16:25.581460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae4725dfad5b'
down_revision: Union[str, None] = '87ffde5400ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title_index', table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title_index', 'tasks', ['title'], unique=False)
    # ### end Alembic commands ###
